services:
  service:
    container_name: bank_system_java
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./data:/info
  database:
    container_name: bank_database
    image: 'postgres:15'
    env_file:
      - .env
    ports:
      - '5433:5432'
